name: Build roadmaps
on: [push]
jobs:
  Build-Roadmaps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build roadmaps
        run: npx zx build/build.mjs
      - name: Commit roadmaps
        run: npx zx .github/commit.mjs -message "build roadmaps"
