name: Build roadmaps
on: [push]
jobs:
  Build-Roadmaps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Rebuild roadmaps if there are changes
        run: |
          npx zx <<'EOF'
          if (await $`git diff skills`) {
            echo('Changes in the skills folder detected');
            echo('Building roadmaps...');
            await $`npx zx build/build.mjs`;
            echo('Commiting roadmaps...');
            await $`npx zx .github/commit.mjs --message "build roadmaps"`;
          } else {
            echo('No changes in the skills folder');
          }
          EOF
        run: npx zx build/build.mjs
        run: npx zx .github/commit.mjs --message "build roadmaps"
