name: Update roadmaps
on:
  push:
    branches:
      - "master"
jobs:
  Update-Roadmaps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Rebuild roadmaps if there are changes
        run: npx zx .github/workflows/update-roadmaps.mjs
